### ISSUE TITLE
Rotating Log Files

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#15]

**Comment by proffapt** [comment]
Elaborate please..

**Comment by sudipnext** [comment]
log rotation is an automated process used in [system administration] in which [log files]are compressed, moved, renamed, or deleted once they are too old or too big.

**Comment by proffapt** [comment]
ok, that's gonna be a new thing apart from notification and gui, which I learnt today.. On my way! to do it.
