### ISSUE TITLE
A Game Written in bash

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#18]

**Comment by NyanCyanide** [comment]
Can I work on this?

**Comment by samarthkumar008** [comment]
Hey there @sudipnext i an work this issue pls assign me

**Comment by samarthkumar008** [comment]
Plz bro assign me this issue i am very excited.

**Comment by sudipnext** [comment]
Good luck with the contribution you are assigned

**Comment by samarthkumar008** [comment]
Bro i am complete this issue please check it bro and merge my request tanku
