### ISSUE TITLE
Calculating Letter Frequencies

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#19]

**Comment by flow6979** [comment]
hey @sudipnext please assign this issue to me. I am very excited to contribute to this issue

**Comment by sudipnext** [comment]
Assigned! Good luck with the Contribution

**Comment by flow6979** [comment]
@sudipnext brother can you please send me link of some youtube video or some resources from which i can learn shell language.
thank you

**Comment by sudipnext** [comment]
A really good GitHub repo I can recommend to you is The art of command line:- https://github.com/jlevy/the-art-of-command-line

**Comment by flow6979** [comment]
> A really good GitHub repo I can recommend to you is The art of command line:- https://github.com/jlevy/the-art-of-command-line

ok bro thanks. i will go through it and will try my best

**Comment by proffapt** [comment]
what to calculate letter frequency in?
words or a file?

**Comment by sudipnext** [comment]
a file! sorry for the incomplete issues

**Comment by proffapt** [comment]
and letter like a, b, c.. or you meant words like 'bash'

and does the user have to input the letter/word needed to count the occurrences for?
@sudipnext

**Comment by sudipnext** [comment]
You solved as i wanted !
