### ISSUE TITLE
Counting files

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#22]

**Comment by ghost** [comment]
Hey @sudipnext I would like to contribute to this issue...
could you specify from where I have to count files? and how to report the final count...

**Comment by sudipnext** [comment]
You need to do it in your own space. Just show the sample it will work!

**Comment by ghost** [comment]
ohh.. @sudipnext means I have to write a python script that will count the number of files present in the directory... right?

**Comment by sudipnext** [comment]
Yes !

**Comment by ghost** [comment]
Okay... could you assign this to me.. @sudipnext

**Comment by sudipnext** [comment]
Assigned to you! Good luck

**Comment by sudipnext** [comment]
Sorry! @Indrajeet-S  the Issue was solved by @proffapt  and successfully merged! try solving another issue :)
