### ISSUE TITLE
 I have a file containing a list of words. I want to sort it in reverse order and print it.

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#29]

**Comment by Shivashish-rwt** [comment]
I can do that. Please assign it to me.

**Comment by sudipnext** [comment]
Assigned to you good luck!

**Comment by Shivashish-rwt** [comment]
@sudipnext 
Please provide me with the file to work on.

**Comment by sudipnext** [comment]
Do on a sample file and do the pull request i will review

**Comment by Shivashish-rwt** [comment]
@sudipnext 
I am unassigning myself due to some urgent work. Sorry for inconvience.

**Comment by mrudul0026** [comment]
@sudipnext, can you review PR #43. Since the issue does not mention to alter the file, script is implemented to just output the result.
