### ISSUE TITLE
Add Scripts to Merge Multiple Files

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#3]

**Comment by flow6979** [comment]
which types of files you wanna merge?
i mean pdf or what?

**Comment by sudipnext** [comment]
PDF's or some sort of any files other than txt

**Comment by whoisYoges** [comment]
@sudipnext assign this to me I can write a bash script to merge two or more pdfs.

**Comment by sudipnext** [comment]
You are assigned! Good Luck!

**Comment by whoisYoges** [comment]
@sudipnext Please Check and review #68
