### ISSUE TITLE
my data file has some repeated lines! How do I get rid of them?

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#30]

**Comment by Saurabh-2809** [comment]
Hi @sudipnext, Can you assign me this task, I would like to contribute to this repo.
And can I use a python script to perform this task?

**Comment by Saurabh-210299** [comment]
Hi @sudipnext, could you please assign me this issue, I am really excited to learn bash scripting and contribute to this repo.
