### ISSUE TITLE
In all of my text files, I want to replace 'sedimentary rocks' with 'earth sciences.' Should I go through and manually edit them all?

### ISSUE THREAD

**Issue by sudipnext** [sudipnext/Bash-scripts-for-easy-life#33]

**Comment by manipta** [comment]
You may upload the file with hacktoberfest label. I can edit it and make a PR. :)

**Comment by sudipnext** [comment]
You can use any file with these words in somewhere between and then Solve the Question! :) 👍 Using Bash, Mannually? don't do that

**Comment by manipta** [comment]
got it. No not manually.

**Comment by mrudul0026** [comment]
@sudipnext , can you assign me this? I have made a script leveraging sed command to do the replacement (PR #40). The script is more flexible as it take the search and replacement string as input.

**Comment by sudipnext** [comment]
Okay open pull request mentioning issue number i will review and merge that
